name: jac_uikit
description: Flutter uikit
version: 0.0.1
homepage: https://github.com/ThinkerJack/jac_uikit

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: